on:
  pull_request:
  push:

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - 8.0
          - 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Add C3.php to index.php
        run: |
          sed -i "5 a require_once dirname(__DIR__) . '/c3.php';" public/index.php
          cat public/index.php

      - name: Run tests with codeception
        run: |
          php -S 127.0.0.1:8080 -t public public/index.php > ./runtime/yii.log 2>&1 &
          vendor/bin/codecept run --coverage-xml

      - name: Upload coverage to codecov
        if: matrix.os == 'ubuntu-latest' && matrix.php == '8.0'
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: tests/_output/coverage.xml
